267	Sentence --> Colloc0s
10	Phoneme --> uh
20	Phoneme --> f
20	Phoneme --> ao
19	Phoneme --> v
74	Phoneme --> l
24	Phoneme --> dh
29	Phoneme --> ah
9	Phoneme --> jh
22	Phoneme --> g
29	Phoneme --> z
57	Phoneme --> r
49	Phoneme --> ih
37	Phoneme --> m
48	Phoneme --> eh
11	Phoneme --> y
15	Phoneme --> sh
87	Phoneme --> ax
11	Phoneme --> ch
2	Phoneme --> zh
28	Phoneme --> w
18	Phoneme --> aw
40	Phoneme --> er
20	Phoneme --> uw
34	Phoneme --> ay
35	Phoneme --> p
47	Phoneme --> iy
7	Phoneme --> th
27	Phoneme --> ey
37	Phoneme --> b
52	Phoneme --> k
7	Phoneme --> oy
41	Phoneme --> ae
63	Phoneme --> d
108	Phoneme --> t
25	Phoneme --> ow
73	Phoneme --> s
22	Phoneme --> hh
20	Phoneme --> aa
7	Phoneme --> ng
83	Phoneme --> n
2042	Colloc0s --> Colloc0 Colloc0s
267	Colloc0s --> Colloc0
485	Colloc0 --> Phonemes
(Colloc0#4 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#3 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#37 (Phonemes (Phoneme ay)))
(Colloc0#6 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme n))))))
(Colloc0#4 (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme v))))
(Colloc0#4 (Phonemes (Phoneme ay) (Phonemes (Phoneme th) (Phonemes (Phoneme ao) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))))
(Colloc0#5 (Phonemes (Phoneme ay) (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme l) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme f))))
(Colloc0#4 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme d))))))
(Colloc0#10 (Phonemes (Phoneme iy) (Phonemes (Phoneme z))))
(Colloc0#2 (Phonemes (Phoneme m)))
(Colloc0#3 (Phonemes (Phoneme m)))
(Colloc0#7 (Phonemes (Phoneme m)))
(Colloc0#12 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#7 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme g) (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ey) (Phonemes (Phoneme v)))))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#11 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme z))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme g) (Phonemes (Phoneme aw) (Phonemes (Phoneme n))))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme t)))))
(Colloc0#12 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))))
(Colloc0#10 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ae))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme er) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ih)))))
(Colloc0#36 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme ow) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme oy))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#1 (Phonemes (Phoneme ch)))
(Colloc0#3 (Phonemes (Phoneme ch)))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#4 (Phonemes (Phoneme v) (Phonemes (Phoneme er))))
(Colloc0#7 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#37 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ih)))
(Colloc0#16 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#3 (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ch) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme ch) (Phonemes (Phoneme ey) (Phonemes (Phoneme n) (Phonemes (Phoneme jh)))))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#29 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#7 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))
(Colloc0#16 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme sh) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme ng)))
(Colloc0#6 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#5 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#2 (Phonemes (Phoneme k)))
(Colloc0#2 (Phonemes (Phoneme k)))
(Colloc0#20 (Phonemes (Phoneme k)))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme d) (Phonemes (Phoneme z))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme t))))))))))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s))))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme dh))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme aw) (Phonemes (Phoneme ch) (Phonemes (Phoneme ax))))))
(Colloc0#13 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#4 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#9 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#4 (Phonemes (Phoneme ax)))
(Colloc0#7 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#18 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme y) (Phonemes (Phoneme ax))))))))
(Colloc0#7 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme jh)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme v))))
(Colloc0#31 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme k))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme r)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ow))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme b))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme oy)))))
(Colloc0#8 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))
(Colloc0#8 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme z) (Phonemes (Phoneme ay)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme z) (Phonemes (Phoneme uw)))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))))
(Colloc0#2 (Phonemes (Phoneme w)))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#13 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme n)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme l)))))
(Colloc0#19 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme dh) (Phonemes (Phoneme dh))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme sh) (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme th)))))))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#26 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme sh)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme eh))))
(Colloc0#14 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme ah)))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme m))))
(Colloc0#12 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#7 (Phonemes (Phoneme ah) (Phonemes (Phoneme v) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#5 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#5 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#5 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#12 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme aw) (Phonemes (Phoneme l))))))))
(Colloc0#36 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ah))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme w) (Phonemes (Phoneme ih))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme oy))))
(Colloc0#2 (Phonemes (Phoneme p)))
(Colloc0#3 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))))
(Colloc0#8 (Phonemes (Phoneme p) (Phonemes (Phoneme r))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#12 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme s) (Phonemes (Phoneme ow)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme oy) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme z))))))
(Colloc0#6 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme p)))))
(Colloc0#7 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ax))))
(Colloc0#5 (Phonemes (Phoneme r) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ao))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#14 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme t))))))))
(Colloc0#11 (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))
(Colloc0#9 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#5 (Phonemes (Phoneme aa) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme b))))))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#7 (Phonemes (Phoneme b)))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh)))))
(Colloc0#8 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ih))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme z)))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme g)))))
(Colloc0#19 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme b)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme p))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme uw)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#11 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#5 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#31 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme t) (Phonemes (Phoneme ow) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme eh))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#8 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#12 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#5 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme v) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))))
(Colloc0#52 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme s) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme ch) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme th) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme b)))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme k))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme k))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme d))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme z))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#2 (Phonemes (Phoneme er)))
(Colloc0#3 (Phonemes (Phoneme er) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme er) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme er) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme er) (Phonemes (Phoneme b))))
(Colloc0#4 (Phonemes (Phoneme er) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#4 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#14 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ih))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme er) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme d))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme z))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme s) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme eh))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#6 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d)))
(Colloc0#5 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme v) (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))))
(Colloc0#6 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#24 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme t) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme v))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g))))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g)))))
(Colloc0#21 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))
(Colloc0#7 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme uw)))
(Colloc0#3 (Phonemes (Phoneme uw)))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))
(Colloc0#3 (Phonemes (Phoneme uw) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme d) (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))))
(Colloc0#69 (Phonemes (Phoneme z)))
(Colloc0#10 (Phonemes (Phoneme z)))
(Colloc0#6 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#4 (Phonemes (Phoneme z) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme f) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#7 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#11 (Phonemes (Phoneme s)))
(Colloc0#9 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme z))))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme b))))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#9 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme th))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme p))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ao))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er)))))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme eh))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme f))))))
(Colloc0#9 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#12 (Phonemes (Phoneme s) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme ey)))
(Colloc0#3 (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme eh)))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme p) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme ax)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s) (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d))))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme sh) (Phonemes (Phoneme ih)))))
(Colloc0#1 (Phonemes (Phoneme dh)))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ih))))
(Colloc0#78 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b)))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#29 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#9 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme er))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))))))))
(Colloc0#1 (Phonemes (Phoneme jh)))
(Colloc0#8 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme jh) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme jh) (Phonemes (Phoneme eh) (Phonemes (Phoneme f)))))
(Colloc0#3 (Phonemes (Phoneme ow)))
(Colloc0#5 (Phonemes (Phoneme ow)))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#6 (Phonemes (Phoneme ow) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme hh)))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay) (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v) (Phonemes (Phoneme ax) (Phonemes (Phoneme r)))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z)))))
(Colloc0#38 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme er) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme sh)))
(Colloc0#1 (Phonemes (Phoneme sh)))
(Colloc0#130 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#17 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme sh) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme ax)))))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme uh))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme f)))
(Colloc0#2 (Phonemes (Phoneme f)))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme b) (Phonemes (Phoneme oy)))))))))))))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme r))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#14 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ae) (Phonemes (Phoneme s)))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s)))))
(Colloc0#8 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme oy)))
(Colloc0#1 (Phonemes (Phoneme aw)))
(Colloc0#4 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme d))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme jh))))
(Colloc0#3 (Phonemes (Phoneme g)))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme r))))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme m))))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme er))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme uw) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#9 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme zh)))
844	Phonemes --> Phoneme Phonemes
485	Phonemes --> Phoneme
