267	Sentence --> Colloc0s
454	Colloc0 --> Phonemes
(Colloc0#1 (Phonemes (Phoneme dh)))
(Colloc0#3 (Phonemes (Phoneme dh)))
(Colloc0#43 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#13 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aw))))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))))))
(Colloc0#46 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#13 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#9 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ao))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme l))))
(Colloc0#8 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#23 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme g)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme z)))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme n)))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#10 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#2 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#26 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme b))))))
(Colloc0#6 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))
(Colloc0#13 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ax)))))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme aw)))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme p) (Phonemes (Phoneme t))))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme sh)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme y) (Phonemes (Phoneme er))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme l) (Phonemes (Phoneme y) (Phonemes (Phoneme ax))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aw)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme ax)))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n))))))
(Colloc0#14 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#6 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))))
(Colloc0#6 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#27 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ow)))))
(Colloc0#4 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#3 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme er) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#6 (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme ng)))))
(Colloc0#23 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t)))))
(Colloc0#6 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#8 (Phonemes (Phoneme aa) (Phonemes (Phoneme b) (Phonemes (Phoneme ax)))))
(Colloc0#9 (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme z))))
(Colloc0#23 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#6 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#5 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#12 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#2 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#3 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#4 (Phonemes (Phoneme k)))
(Colloc0#4 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme th) (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme v) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme v) (Phonemes (Phoneme er) (Phonemes (Phoneme iy))))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme uh))))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#10 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#8 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#7 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))
(Colloc0#13 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme eh))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme th))))))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme p)))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme ch) (Phonemes (Phoneme uw) (Phonemes (Phoneme ey)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme n)))))
(Colloc0#9 (Phonemes (Phoneme s) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ao))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme p))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme uw) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme dh)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme ch) (Phonemes (Phoneme t))))))
(Colloc0#21 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#13 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#20 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#10 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#9 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme s)))))
(Colloc0#10 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme d) (Phonemes (Phoneme z))))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ih))))
(Colloc0#19 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#25 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme v)))))
(Colloc0#11 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme y)))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme d))))))
(Colloc0#39 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#51 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme uh) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme ch) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme z))))
(Colloc0#17 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#83 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#7 (Phonemes (Phoneme zh) (Phonemes (Phoneme ax))))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#13 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme m) (Phonemes (Phoneme w))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k)))))
(Colloc0#40 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme er) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme t)))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme r))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))))
(Colloc0#6 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#13 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme ay)))))
(Colloc0#22 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))))
(Colloc0#1 (Phonemes (Phoneme ch)))
(Colloc0#4 (Phonemes (Phoneme ch) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme ch) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ow))))))
(Colloc0#1 (Phonemes (Phoneme ch) (Phonemes (Phoneme ey) (Phonemes (Phoneme n) (Phonemes (Phoneme jh) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))))
(Colloc0#9 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme f))))
(Colloc0#20 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#4 (Phonemes (Phoneme ah) (Phonemes (Phoneme n))))
(Colloc0#5 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s)))))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#49 (Phonemes (Phoneme z)))
(Colloc0#17 (Phonemes (Phoneme z)))
(Colloc0#6 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax)))))
(Colloc0#5 (Phonemes (Phoneme z) (Phonemes (Phoneme d))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#18 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme p)))))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme s))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ah)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme th)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme y) (Phonemes (Phoneme er))))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme z))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme aa)))))))))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#3 (Phonemes (Phoneme er) (Phonemes (Phoneme z))))
(Colloc0#3 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme b) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme n))))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih))))
(Colloc0#13 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#5 (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme ch)))))
(Colloc0#6 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme n)))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme ih)))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme eh))))))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))
(Colloc0#15 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#41 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme ih) (Phonemes (Phoneme r))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme f))))
(Colloc0#22 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme d))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme v) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#11 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme ch) (Phonemes (Phoneme ow)))))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme ao) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme ey) (Phonemes (Phoneme m) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme hh)))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme f)))))
(Colloc0#12 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#24 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme er) (Phonemes (Phoneme ow) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme l) (Phonemes (Phoneme f) (Phonemes (Phoneme er)))))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme sh) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))
(Colloc0#164 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ow))))
(Colloc0#4 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch)))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme z))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme f))))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme ow)))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme y) (Phonemes (Phoneme ae)))))
(Colloc0#4 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme p))))
(Colloc0#3 (Phonemes (Phoneme f)))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ax))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme ah)))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme m))))))
(Colloc0#10 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme l))))
(Colloc0#13 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#4 (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme v)))
(Colloc0#2 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme d))))
(Colloc0#6 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er))))))
(Colloc0#15 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))))
(Colloc0#11 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#22 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#17 (Phonemes (Phoneme n) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#11 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme jh))))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme uw))))
(Colloc0#11 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#4 (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme s) (Phonemes (Phoneme ow))))))
(Colloc0#16 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#17 (Phonemes (Phoneme ay)))
(Colloc0#34 (Phonemes (Phoneme ay)))
(Colloc0#11 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme v))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme v) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme ay))))
(Colloc0#4 (Phonemes (Phoneme ey) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme jh)))
(Colloc0#1 (Phonemes (Phoneme jh)))
(Colloc0#2 (Phonemes (Phoneme jh) (Phonemes (Phoneme ax) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ih))))))
(Colloc0#9 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme y))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme er))))
(Colloc0#12 (Phonemes (Phoneme p) (Phonemes (Phoneme r))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ch) (Phonemes (Phoneme er)))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme p) (Phonemes (Phoneme ey))))))))
(Colloc0#12 (Phonemes (Phoneme p) (Phonemes (Phoneme oy) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))
(Colloc0#4 (Phonemes (Phoneme th)))
(Colloc0#39 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#6 (Phonemes (Phoneme th) (Phonemes (Phoneme ao) (Phonemes (Phoneme t)))))
2186	Colloc0s --> Colloc0 Colloc0s
267	Colloc0s --> Colloc0
830	Phonemes --> Phoneme Phonemes
454	Phonemes --> Phoneme
53	Phoneme --> l
54	Phoneme --> d
28	Phoneme --> ow
45	Phoneme --> ih
27	Phoneme --> ey
61	Phoneme --> k
18	Phoneme --> hh
43	Phoneme --> eh
13	Phoneme --> y
39	Phoneme --> er
104	Phoneme --> ax
21	Phoneme --> uw
42	Phoneme --> m
19	Phoneme --> ao
48	Phoneme --> r
27	Phoneme --> ay
13	Phoneme --> ch
7	Phoneme --> jh
19	Phoneme --> g
13	Phoneme --> aw
39	Phoneme --> p
24	Phoneme --> dh
28	Phoneme --> ah
26	Phoneme --> w
88	Phoneme --> t
74	Phoneme --> n
40	Phoneme --> b
7	Phoneme --> sh
2	Phoneme --> zh
3	Phoneme --> oy
10	Phoneme --> uh
10	Phoneme --> ng
59	Phoneme --> iy
21	Phoneme --> f
21	Phoneme --> aa
85	Phoneme --> s
36	Phoneme --> z
17	Phoneme --> v
7	Phoneme --> th
31	Phoneme --> ae
