#!/usr/bin/env python
"""This script is used to check and optionnaly correct an utterances file.

Copyright 2015 Mathieu Bernard.

"""

import argparse
from phonologizer import check_file


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('input',
                        help='input text file to be checked')
    parser.add_argument('-o', '--output',
                        help='output corrected file. If not specifed, '
                        'do not correct anything and raise on the first error.',
                        default=None)
    args = parser.parse_args()

    on_error = 'raise' if args.output is None else 'correct'
    if on_error == 'raise':
        check_file(args.input, on_error)
    else:
        open(args.output, 'w').write(check_file(args.input, on_error))


if __name__ == '__main__':
    main()
