825	Sentence --> Colloc0s
1735	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
1034	Phonemes --> Phoneme Phonemes
410	Phonemes --> Phoneme
19	Phoneme --> v
59	Phoneme --> ih
68	Phoneme --> iy
101	Phoneme --> t
91	Phoneme --> ax
1	Phoneme --> zh
79	Phoneme --> s
14	Phoneme --> ng
12	Phoneme --> sh
32	Phoneme --> ow
38	Phoneme --> uw
17	Phoneme --> aw
3	Phoneme --> oy
31	Phoneme --> hh
31	Phoneme --> p
60	Phoneme --> d
37	Phoneme --> dh
55	Phoneme --> r
35	Phoneme --> w
74	Phoneme --> n
7	Phoneme --> jh
59	Phoneme --> l
33	Phoneme --> ae
36	Phoneme --> b
41	Phoneme --> eh
37	Phoneme --> m
31	Phoneme --> f
17	Phoneme --> y
39	Phoneme --> ay
35	Phoneme --> er
14	Phoneme --> uh
37	Phoneme --> z
44	Phoneme --> aa
21	Phoneme --> ao
6	Phoneme --> th
25	Phoneme --> g
29	Phoneme --> ah
11	Phoneme --> ch
73	Phoneme --> k
30	Phoneme --> ey
410	Colloc0 --> Phonemes
(Colloc0#16 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme f)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ae))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ay) (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme ch)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme dh)))))
(Colloc0#42 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#53 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#18 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme d) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax)))))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#31 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme m))))))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme v) (Phonemes (Phoneme er))))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v) (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme uw)))
(Colloc0#4 (Phonemes (Phoneme uw) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng)))))
(Colloc0#12 (Phonemes (Phoneme uw) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme uw) (Phonemes (Phoneme p))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme r))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#25 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#7 (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))))
(Colloc0#17 (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))))
(Colloc0#19 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme k)))))
(Colloc0#12 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d)))))))))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme er))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#9 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#6 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#8 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k) (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#9 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))
(Colloc0#12 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#1 (Phonemes (Phoneme ng) (Phonemes (Phoneme ax) (Phonemes (Phoneme p)))))
(Colloc0#6 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ih))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ae))))
(Colloc0#15 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#23 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme y) (Phonemes (Phoneme uw)))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme k))))))))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme z))))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme s))))
(Colloc0#21 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#25 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aw) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme f) (Phonemes (Phoneme iy))))))
(Colloc0#15 (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme y)))
(Colloc0#58 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#5 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))))))
(Colloc0#9 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#38 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#13 (Phonemes (Phoneme z)))
(Colloc0#42 (Phonemes (Phoneme z)))
(Colloc0#10 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#5 (Phonemes (Phoneme z) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme d)))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme t))))))
(Colloc0#11 (Phonemes (Phoneme z) (Phonemes (Phoneme sh) (Phonemes (Phoneme uw)))))
(Colloc0#4 (Phonemes (Phoneme dh)))
(Colloc0#10 (Phonemes (Phoneme dh)))
(Colloc0#2 (Phonemes (Phoneme dh)))
(Colloc0#47 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#22 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#11 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ax)))))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#36 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#40 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))))
(Colloc0#7 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme aa) (Phonemes (Phoneme r)))))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g) (Phonemes (Phoneme iy))))))))))
(Colloc0#24 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#8 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme er))))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme y))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme aw) (Phonemes (Phoneme er)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme d))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#18 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme k)))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme n)))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax) (Phonemes (Phoneme f)))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme oy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))
(Colloc0#14 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#20 (Phonemes (Phoneme ao) (Phonemes (Phoneme g) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))))
(Colloc0#8 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#10 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme v)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme v) (Phonemes (Phoneme dh))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#28 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme jh) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme hh)))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme uw) (Phonemes (Phoneme z) (Phonemes (Phoneme iy))))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ao))))
(Colloc0#27 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh) (Phonemes (Phoneme b) (Phonemes (Phoneme iy)))))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme hh) (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))))
(Colloc0#14 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme dh)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme g))))))))))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme uw) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#13 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#11 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh)))))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))))
(Colloc0#10 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme eh) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#8 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme f) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))))
(Colloc0#6 (Phonemes (Phoneme ay) (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k)))))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t))))))
(Colloc0#8 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme v) (Phonemes (Phoneme g) (Phonemes (Phoneme aa))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))))))
(Colloc0#7 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#12 (Phonemes (Phoneme d)))
(Colloc0#15 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme s)))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))))))))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme b) (Phonemes (Phoneme iy)))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme r))))
(Colloc0#16 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa) (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme uh))))))))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme aa))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#13 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#11 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme ax))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme v))))
(Colloc0#13 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#4 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))))
(Colloc0#5 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))))
(Colloc0#3 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme m)))))
(Colloc0#12 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#5 (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme p))))
(Colloc0#7 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))))))))))
(Colloc0#13 (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t))))))))
(Colloc0#6 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme aw) (Phonemes (Phoneme ay)))))
(Colloc0#12 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#36 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh))))))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#9 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er)))))))
(Colloc0#31 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme k))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme ng))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t) (Phonemes (Phoneme dh)))))))
(Colloc0#17 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme l))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k))))))
(Colloc0#13 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme uw)))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s))))))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme ah)))
(Colloc0#4 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#3 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ax))))))))))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#10 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))))
(Colloc0#9 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))
(Colloc0#7 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme aa))))
(Colloc0#27 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#13 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng) (Phonemes (Phoneme k) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch)))))
(Colloc0#5 (Phonemes (Phoneme ow)))
(Colloc0#35 (Phonemes (Phoneme ow)))
(Colloc0#3 (Phonemes (Phoneme ow)))
(Colloc0#11 (Phonemes (Phoneme ow)))
(Colloc0#9 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme ax)))))))
(Colloc0#11 (Phonemes (Phoneme ow) (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme r))))))
(Colloc0#7 (Phonemes (Phoneme ow) (Phonemes (Phoneme n))))
(Colloc0#8 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))))))))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#1 (Phonemes (Phoneme v) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))))))))
(Colloc0#1 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))))))
(Colloc0#7 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#2 (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme f)))))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#20 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ey))))
(Colloc0#11 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay) (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#21 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme v) (Phonemes (Phoneme ay) (Phonemes (Phoneme z)))))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme g)))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#15 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v) (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme m))))))
(Colloc0#8 (Phonemes (Phoneme g) (Phonemes (Phoneme ao) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))))))))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#16 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme er))))
(Colloc0#13 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#21 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s) (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme s) (Phonemes (Phoneme iy)))))))))))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme ch) (Phonemes (Phoneme ey) (Phonemes (Phoneme ch))))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#9 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#6 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ey) (Phonemes (Phoneme v)))))
(Colloc0#8 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy) (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme uh) (Phonemes (Phoneme r) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme ch) (Phonemes (Phoneme p)))))))))
(Colloc0#2 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ch) (Phonemes (Phoneme er)))))))
(Colloc0#18 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh))))))
(Colloc0#14 (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))
(Colloc0#15 (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))))
(Colloc0#16 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme ch) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme s)))))
(Colloc0#11 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))))))
