825	Sentence --> Colloc0s
2000	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
826	Phonemes --> Phoneme Phonemes
397	Phonemes --> Phoneme
18	Phoneme --> v
48	Phoneme --> ih
58	Phoneme --> iy
90	Phoneme --> t
71	Phoneme --> ax
1	Phoneme --> zh
63	Phoneme --> s
17	Phoneme --> ng
12	Phoneme --> sh
28	Phoneme --> ow
30	Phoneme --> uw
13	Phoneme --> aw
3	Phoneme --> oy
30	Phoneme --> hh
28	Phoneme --> p
49	Phoneme --> d
20	Phoneme --> dh
46	Phoneme --> r
31	Phoneme --> w
60	Phoneme --> n
7	Phoneme --> jh
54	Phoneme --> l
29	Phoneme --> ae
28	Phoneme --> b
42	Phoneme --> eh
42	Phoneme --> m
28	Phoneme --> f
10	Phoneme --> y
32	Phoneme --> ay
31	Phoneme --> er
9	Phoneme --> uh
30	Phoneme --> z
31	Phoneme --> aa
17	Phoneme --> ao
6	Phoneme --> th
21	Phoneme --> g
24	Phoneme --> ah
10	Phoneme --> ch
65	Phoneme --> k
29	Phoneme --> ey
397	Colloc0 --> Phonemes
(Colloc0#3 (Phonemes (Phoneme w)))
(Colloc0#16 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme f)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme ch)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme dh)))))
(Colloc0#42 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#53 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#18 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#31 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme m))))))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme er)))))))
(Colloc0#9 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#11 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme v) (Phonemes (Phoneme er))))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme ax)))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme uw)))
(Colloc0#12 (Phonemes (Phoneme uw) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme p))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme p))))
(Colloc0#1 (Phonemes (Phoneme ih)))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#26 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))))
(Colloc0#17 (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))))
(Colloc0#32 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#19 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er)))))
(Colloc0#9 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#9 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng)))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme k)))))
(Colloc0#9 (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh)))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#6 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#7 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#6 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#8 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k) (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#9 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#1 (Phonemes (Phoneme ng)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#2 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme w))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme k)))))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ae))))
(Colloc0#38 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme d)))))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s))))))
(Colloc0#12 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#35 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme v)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aw) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme f) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme uh))))
(Colloc0#98 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#38 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme er) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#3 (Phonemes (Phoneme z)))
(Colloc0#50 (Phonemes (Phoneme z)))
(Colloc0#7 (Phonemes (Phoneme z)))
(Colloc0#2 (Phonemes (Phoneme z) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme t))))))
(Colloc0#9 (Phonemes (Phoneme z) (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))))
(Colloc0#9 (Phonemes (Phoneme z) (Phonemes (Phoneme sh) (Phonemes (Phoneme uw)))))
(Colloc0#1 (Phonemes (Phoneme dh)))
(Colloc0#80 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#83 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))
(Colloc0#40 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#15 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#6 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#24 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#8 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme b)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d)))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#11 (Phonemes (Phoneme t) (Phonemes (Phoneme aw) (Phonemes (Phoneme er)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme aw) (Phonemes (Phoneme ay))))))
(Colloc0#21 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme k)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme hh) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme oy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme ng))))
(Colloc0#14 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#8 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#10 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme v)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#39 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#35 (Phonemes (Phoneme s)))
(Colloc0#10 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme w))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme f))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme uw) (Phonemes (Phoneme z) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ao) (Phonemes (Phoneme ax)))))
(Colloc0#29 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme b)))))
(Colloc0#16 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#11 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme k))))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#11 (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme m))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme p))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))))
(Colloc0#16 (Phonemes (Phoneme b)))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme uw) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme d))))))
(Colloc0#6 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ae))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay))))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))))
(Colloc0#10 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#21 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme eh) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#26 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#3 (Phonemes (Phoneme ay)))
(Colloc0#7 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t))))))
(Colloc0#6 (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))))
(Colloc0#8 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme v) (Phonemes (Phoneme g) (Phonemes (Phoneme aa))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))))))
(Colloc0#15 (Phonemes (Phoneme ay) (Phonemes (Phoneme eh) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#22 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#7 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme r)))))))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))))))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))
(Colloc0#16 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme y) (Phonemes (Phoneme uw)))))
(Colloc0#13 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#22 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme z) (Phonemes (Phoneme s))))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k)))))
(Colloc0#13 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))
(Colloc0#8 (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme v) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#43 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#17 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))))))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))))))))))
(Colloc0#13 (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#10 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#14 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#5 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#40 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh))))))))))
(Colloc0#14 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#11 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#2 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))))
(Colloc0#24 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))
(Colloc0#17 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme m))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#13 (Phonemes (Phoneme ah) (Phonemes (Phoneme ng) (Phonemes (Phoneme k) (Phonemes (Phoneme iy))))))
(Colloc0#5 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#6 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme ch))))
(Colloc0#2 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#3 (Phonemes (Phoneme m)))
(Colloc0#3 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#6 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ih))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ey))))
(Colloc0#10 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#9 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))
(Colloc0#7 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m)))))
(Colloc0#27 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#45 (Phonemes (Phoneme ow)))
(Colloc0#4 (Phonemes (Phoneme ow)))
(Colloc0#17 (Phonemes (Phoneme ow)))
(Colloc0#1 (Phonemes (Phoneme ow)))
(Colloc0#8 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme f)))))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme m))))
(Colloc0#8 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#6 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme v) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))))))))
(Colloc0#7 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#4 (Phonemes (Phoneme er) (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme hh)))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#20 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ey))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay) (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#21 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme v) (Phonemes (Phoneme ay) (Phonemes (Phoneme z)))))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme g)))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme er) (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme b))))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v) (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme m))))))
(Colloc0#8 (Phonemes (Phoneme g) (Phonemes (Phoneme ao) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#22 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme er))))
(Colloc0#13 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#21 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme eh)))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme f)))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))))))))
(Colloc0#6 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme ch) (Phonemes (Phoneme ey) (Phonemes (Phoneme ch))))))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme jh) (Phonemes (Phoneme eh)))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#10 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#7 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ey) (Phonemes (Phoneme v)))))
(Colloc0#8 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme uh) (Phonemes (Phoneme r) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme ch) (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t))))))))))))
(Colloc0#3 (Phonemes (Phoneme p)))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ch) (Phonemes (Phoneme er) (Phonemes (Phoneme ah) (Phonemes (Phoneme v)))))))))
(Colloc0#18 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#14 (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k)))))
(Colloc0#15 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#19 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme ch) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme s)))))
(Colloc0#11 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
