825	Sentence --> Colloc0s
468	Colloc0 --> Phonemes
(Colloc0#1 (Phonemes (Phoneme dh)))
(Colloc0#49 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme m))))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow))))
(Colloc0#7 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#130 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#6 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))
(Colloc0#41 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))))
(Colloc0#87 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#17 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))))
(Colloc0#6 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#14 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#5 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme n))))
(Colloc0#20 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme ch)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme z) (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme uw) (Phonemes (Phoneme v))))))))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme g) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme z) (Phonemes (Phoneme ay))))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme f) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#41 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#6 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))))
(Colloc0#14 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch) (Phonemes (Phoneme t))))))))))
(Colloc0#35 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#47 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#3 (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme f))))
(Colloc0#4 (Phonemes (Phoneme t)))
(Colloc0#5 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme l) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme s)))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#10 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch)))))
(Colloc0#17 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#46 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))))
(Colloc0#11 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ay))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme z))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))))
(Colloc0#12 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme p)))))
(Colloc0#10 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme oy))))
(Colloc0#9 (Phonemes (Phoneme t) (Phonemes (Phoneme oy) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme z)))
(Colloc0#4 (Phonemes (Phoneme z)))
(Colloc0#3 (Phonemes (Phoneme z)))
(Colloc0#5 (Phonemes (Phoneme z)))
(Colloc0#14 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#25 (Phonemes (Phoneme z)))
(Colloc0#6 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#2 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme t))))))
(Colloc0#6 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))))
(Colloc0#4 (Phonemes (Phoneme z) (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))))
(Colloc0#1 (Phonemes (Phoneme ah)))
(Colloc0#15 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#18 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme p)))))
(Colloc0#11 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#10 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme y) (Phonemes (Phoneme ah) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme y) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#29 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#65 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#108 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#26 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme uh) (Phonemes (Phoneme r)))))
(Colloc0#29 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#2 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme z))))))
(Colloc0#10 (Phonemes (Phoneme aa) (Phonemes (Phoneme p))))
(Colloc0#20 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#26 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#8 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#34 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#11 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme oy) (Phonemes (Phoneme n)))))
(Colloc0#21 (Phonemes (Phoneme ow)))
(Colloc0#27 (Phonemes (Phoneme ow)))
(Colloc0#12 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#26 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#6 (Phonemes (Phoneme ow) (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng))))))
(Colloc0#1 (Phonemes (Phoneme p)))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme aa) (Phonemes (Phoneme b) (Phonemes (Phoneme ax)))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme k))))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme eh) (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax)))))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#11 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme th))))))))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme l)))))
(Colloc0#8 (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh))))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme s)))))
(Colloc0#25 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme l)))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#16 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#33 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme g))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme iy)))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))))
(Colloc0#80 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme f))))))
(Colloc0#8 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme v) (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ey)))))
(Colloc0#6 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ih)))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme b))))
(Colloc0#28 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#4 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#29 (Phonemes (Phoneme s)))
(Colloc0#15 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme z)))))
(Colloc0#12 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme ch) (Phonemes (Phoneme uw) (Phonemes (Phoneme ey) (Phonemes (Phoneme sh))))))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme th))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme aa) (Phonemes (Phoneme f) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ow) (Phonemes (Phoneme f)))))
(Colloc0#13 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme er)))))))
(Colloc0#13 (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#25 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme y) (Phonemes (Phoneme uw)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme f)))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#25 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch) (Phonemes (Phoneme er) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme y) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh))))))))))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ay) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#9 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme f)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#15 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#4 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#2 (Phonemes (Phoneme n)))
(Colloc0#5 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#30 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#7 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#3 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#5 (Phonemes (Phoneme ay) (Phonemes (Phoneme z))))
(Colloc0#5 (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#5 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme ax)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme n) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme b) (Phonemes (Phoneme ay)))))))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme sh) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme ow)))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme f) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme z))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ah))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))))
(Colloc0#18 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#27 (Phonemes (Phoneme m) (Phonemes (Phoneme er) (Phonemes (Phoneme iy)))))
(Colloc0#10 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme uw)))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme th)))))
(Colloc0#6 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme er)))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#8 (Phonemes (Phoneme er) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme ax)))))
(Colloc0#4 (Phonemes (Phoneme hh)))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#28 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#12 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#13 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z)))))
(Colloc0#11 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))
(Colloc0#13 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#29 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#3 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ey))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#17 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme uw) (Phonemes (Phoneme jh) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme w)))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#17 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#29 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#27 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#21 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#14 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme ch)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ay) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme v)))))
(Colloc0#19 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#10 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme f)))))
(Colloc0#3 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme m))))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme ih))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#8 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme p))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))
(Colloc0#31 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme ng)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme v)))))
(Colloc0#7 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#16 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g))))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l)))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#14 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ay) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme er))))
(Colloc0#31 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#6 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#13 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme n) (Phonemes (Phoneme jh) (Phonemes (Phoneme er) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))))))
(Colloc0#15 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#2 (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy)))))
(Colloc0#2 (Phonemes (Phoneme ey) (Phonemes (Phoneme ch))))
(Colloc0#5 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme eh)))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#13 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#8 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#13 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh) (Phonemes (Phoneme b))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))
(Colloc0#10 (Phonemes (Phoneme b) (Phonemes (Phoneme uw) (Phonemes (Phoneme m)))))
(Colloc0#6 (Phonemes (Phoneme b) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme l))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme ow)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))
(Colloc0#8 (Phonemes (Phoneme b) (Phonemes (Phoneme ey) (Phonemes (Phoneme b)))))
(Colloc0#29 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#1 (Phonemes (Phoneme ch)))
(Colloc0#26 (Phonemes (Phoneme ch) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#7 (Phonemes (Phoneme ch) (Phonemes (Phoneme ey) (Phonemes (Phoneme n) (Phonemes (Phoneme jh))))))
(Colloc0#2 (Phonemes (Phoneme ch) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme zh) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))))
(Colloc0#27 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#3 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme sh)))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme ae) (Phonemes (Phoneme l)))))
(Colloc0#10 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme z)))))))))
(Colloc0#22 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme sh) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#14 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#8 (Phonemes (Phoneme iy)))
(Colloc0#4 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#5 (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#6 (Phonemes (Phoneme iy) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme f)))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme m))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#10 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme er))))
(Colloc0#19 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme v) (Phonemes (Phoneme er) (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme l) (Phonemes (Phoneme z))))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme th)))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme ow)))))
(Colloc0#1 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#5 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#6 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng)))))
(Colloc0#3 (Phonemes (Phoneme jh)))
(Colloc0#10 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme aa) (Phonemes (Phoneme b) (Phonemes (Phoneme dh) (Phonemes (Phoneme ow)))))))
(Colloc0#7 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
29	Phoneme --> ow
20	Phoneme --> ao
50	Phoneme --> ih
44	Phoneme --> m
54	Phoneme --> z
66	Phoneme --> iy
31	Phoneme --> ey
15	Phoneme --> v
5	Phoneme --> oy
51	Phoneme --> k
31	Phoneme --> w
18	Phoneme --> g
44	Phoneme --> eh
2	Phoneme --> zh
43	Phoneme --> ay
34	Phoneme --> f
13	Phoneme --> sh
9	Phoneme --> aw
45	Phoneme --> p
22	Phoneme --> dh
55	Phoneme --> d
12	Phoneme --> ch
76	Phoneme --> ax
26	Phoneme --> uw
12	Phoneme --> th
62	Phoneme --> s
56	Phoneme --> r
35	Phoneme --> aa
16	Phoneme --> ng
65	Phoneme --> n
67	Phoneme --> l
29	Phoneme --> er
99	Phoneme --> t
10	Phoneme --> jh
39	Phoneme --> ah
11	Phoneme --> uh
36	Phoneme --> b
14	Phoneme --> y
28	Phoneme --> hh
35	Phoneme --> ae
2469	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
903	Phonemes --> Phoneme Phonemes
468	Phonemes --> Phoneme
