825	Sentence --> Colloc0s
2615	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
1161	Phonemes --> Phoneme Phonemes
536	Phonemes --> Phoneme
36	Phoneme --> ow
37	Phoneme --> ey
33	Phoneme --> w
40	Phoneme --> p
54	Phoneme --> ih
17	Phoneme --> aw
1	Phoneme --> zh
15	Phoneme --> uh
55	Phoneme --> eh
9	Phoneme --> sh
76	Phoneme --> l
45	Phoneme --> er
43	Phoneme --> ah
21	Phoneme --> y
11	Phoneme --> th
48	Phoneme --> z
52	Phoneme --> m
63	Phoneme --> b
36	Phoneme --> f
25	Phoneme --> ao
29	Phoneme --> dh
78	Phoneme --> k
105	Phoneme --> ax
34	Phoneme --> hh
41	Phoneme --> aa
12	Phoneme --> ng
92	Phoneme --> n
129	Phoneme --> t
4	Phoneme --> oy
51	Phoneme --> ae
42	Phoneme --> ay
33	Phoneme --> g
62	Phoneme --> d
77	Phoneme --> iy
70	Phoneme --> r
9	Phoneme --> jh
22	Phoneme --> v
31	Phoneme --> uw
89	Phoneme --> s
8	Phoneme --> ch
536	Colloc0 --> Phonemes
(Colloc0#5 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d)))
(Colloc0#3 (Phonemes (Phoneme d)))
(Colloc0#9 (Phonemes (Phoneme d) (Phonemes (Phoneme ah))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#14 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#11 (Phonemes (Phoneme d) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme l)))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme z) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))))
(Colloc0#18 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme er) (Phonemes (Phoneme t))))))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ax))))
(Colloc0#36 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme er) (Phonemes (Phoneme f)))))
(Colloc0#18 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g)))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#24 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#12 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#2 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme er))))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme s))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#15 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme y) (Phonemes (Phoneme uw)))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme f) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ey))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ih))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme ay) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme er)))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme t)))))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aw))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme k) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme ah)))
(Colloc0#8 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme er) (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme g)))))))))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme y)))))
(Colloc0#22 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme v) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))))))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme f) (Phonemes (Phoneme iy)))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#8 (Phonemes (Phoneme s)))
(Colloc0#4 (Phonemes (Phoneme s)))
(Colloc0#13 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#9 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#3 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme uw) (Phonemes (Phoneme uw))))))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme z) (Phonemes (Phoneme l))))))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ae) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme l) (Phonemes (Phoneme er))))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme m))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#16 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme iy)))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme uw) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme p))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ao) (Phonemes (Phoneme dh)))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ao) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ao) (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ow) (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch)))))))
(Colloc0#21 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))))
(Colloc0#4 (Phonemes (Phoneme ae) (Phonemes (Phoneme r) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#19 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#6 (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#88 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme m))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme v)))))))
(Colloc0#3 (Phonemes (Phoneme ae) (Phonemes (Phoneme f) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#6 (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#1 (Phonemes (Phoneme dh)))
(Colloc0#81 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#67 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#32 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m)))))
(Colloc0#9 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#62 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#28 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#6 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))))
(Colloc0#10 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))))
(Colloc0#1 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))))
(Colloc0#7 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#21 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#14 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme eh)))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme d))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))
(Colloc0#6 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))
(Colloc0#7 (Phonemes (Phoneme eh) (Phonemes (Phoneme g))))
(Colloc0#7 (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme f))))
(Colloc0#10 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ax)))))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))))
(Colloc0#8 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme g)))))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme aa) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme z))))))))
(Colloc0#6 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme v) (Phonemes (Phoneme er))))))
(Colloc0#40 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme eh))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme m)))))
(Colloc0#57 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme g) (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme th)))))))))
(Colloc0#17 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme y) (Phonemes (Phoneme aa) (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme y) (Phonemes (Phoneme ax)))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))))))))
(Colloc0#1 (Phonemes (Phoneme ey)))
(Colloc0#1 (Phonemes (Phoneme ey) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme z))))))
(Colloc0#2 (Phonemes (Phoneme ey) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme ey) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme b)))))
(Colloc0#3 (Phonemes (Phoneme ey) (Phonemes (Phoneme m))))
(Colloc0#3 (Phonemes (Phoneme ey) (Phonemes (Phoneme ch))))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#12 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme k))))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#13 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ey))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme ay)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ah))))
(Colloc0#10 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#14 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme th)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme r))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme b)))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng))))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme t))))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d) (Phonemes (Phoneme n) (Phonemes (Phoneme uw) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme d))))))))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme ae))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ay))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))))
(Colloc0#9 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme uw)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme uw) (Phonemes (Phoneme b)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme z))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme aw))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t)))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#19 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))
(Colloc0#45 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#22 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#12 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))))
(Colloc0#12 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#7 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#112 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#10 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#3 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#5 (Phonemes (Phoneme ay)))
(Colloc0#1 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme s) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#4 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme v))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme sh) (Phonemes (Phoneme uh) (Phonemes (Phoneme r))))))))))
(Colloc0#2 (Phonemes (Phoneme g)))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme ah) (Phonemes (Phoneme s)))))
(Colloc0#10 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))))))
(Colloc0#11 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#6 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#8 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme ow) (Phonemes (Phoneme ax) (Phonemes (Phoneme hh))))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme ow) (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))))
(Colloc0#18 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#2 (Phonemes (Phoneme ax)))
(Colloc0#26 (Phonemes (Phoneme ax)))
(Colloc0#6 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#2 (Phonemes (Phoneme ax)))
(Colloc0#7 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#2 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme d))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme k))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ao) (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme oy)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme b))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#12 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme s) (Phonemes (Phoneme iy)))))))
(Colloc0#7 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme n)))))))
(Colloc0#9 (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme t)))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme n) (Phonemes (Phoneme z)))))))
(Colloc0#19 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#25 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme f))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme f) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme ow))))))
(Colloc0#5 (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme jh))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme m))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme uw) (Phonemes (Phoneme v) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme l))))))
(Colloc0#38 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ae) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#10 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme m) (Phonemes (Phoneme iy)))))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme l) (Phonemes (Phoneme iy)))))))
(Colloc0#9 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#41 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme er) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme aw))))
(Colloc0#20 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme uw) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme r))))))
(Colloc0#5 (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme s) (Phonemes (Phoneme t)))))))
(Colloc0#6 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme uw))))
(Colloc0#25 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#12 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))
(Colloc0#20 (Phonemes (Phoneme z)))
(Colloc0#10 (Phonemes (Phoneme z)))
(Colloc0#16 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#21 (Phonemes (Phoneme z)))
(Colloc0#7 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme z) (Phonemes (Phoneme ay) (Phonemes (Phoneme l) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme p)))))
(Colloc0#4 (Phonemes (Phoneme z) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v))))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme w))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ao) (Phonemes (Phoneme f)))))
(Colloc0#4 (Phonemes (Phoneme z) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme w)))
(Colloc0#118 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#39 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#20 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))))))))
(Colloc0#24 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme ch)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ax) (Phonemes (Phoneme dh)))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme er))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aw))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))))
(Colloc0#20 (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme hh)))
(Colloc0#1 (Phonemes (Phoneme hh)))
(Colloc0#15 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z)))))
(Colloc0#13 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme p))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme aa) (Phonemes (Phoneme hh) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ey))))
(Colloc0#17 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#8 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw))))
(Colloc0#6 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#8 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme hh)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#17 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#13 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#1 (Phonemes (Phoneme er) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme er) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#3 (Phonemes (Phoneme er) (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#2 (Phonemes (Phoneme v) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme m))))))))
(Colloc0#2 (Phonemes (Phoneme v) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ax))))))
(Colloc0#8 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme ao)))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme s))))
(Colloc0#6 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#4 (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme jh)))))))
(Colloc0#17 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#5 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#4 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#6 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme jh)))
(Colloc0#2 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme n) (Phonemes (Phoneme z))))))))))
(Colloc0#2 (Phonemes (Phoneme jh) (Phonemes (Phoneme ey))))
(Colloc0#10 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw))))
(Colloc0#4 (Phonemes (Phoneme jh) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme y) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#9 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#4 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#31 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#4 (Phonemes (Phoneme y) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme n))))))
(Colloc0#107 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#11 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme w) (Phonemes (Phoneme er) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))))))
(Colloc0#6 (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme f))))))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme ow) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme uh) (Phonemes (Phoneme r)))))
(Colloc0#21 (Phonemes (Phoneme ow)))
(Colloc0#2 (Phonemes (Phoneme ow)))
(Colloc0#2 (Phonemes (Phoneme ow)))
(Colloc0#44 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme iy)))))))))
(Colloc0#2 (Phonemes (Phoneme ow) (Phonemes (Phoneme ax))))
(Colloc0#4 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme f)))
(Colloc0#1 (Phonemes (Phoneme f)))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ao) (Phonemes (Phoneme ng)))))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme v) (Phonemes (Phoneme er) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme ah))))))))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ih))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme l))))
(Colloc0#8 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme er))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#69 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme l))))
(Colloc0#3 (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))
(Colloc0#9 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#10 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#4 (Phonemes (Phoneme iy)))
(Colloc0#9 (Phonemes (Phoneme iy)))
(Colloc0#6 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#6 (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#7 (Phonemes (Phoneme iy) (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme n))))))
(Colloc0#5 (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))
(Colloc0#1 (Phonemes (Phoneme m)))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme g)))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ae) (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme ay) (Phonemes (Phoneme k))))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme sh) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))))))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ay) (Phonemes (Phoneme v) (Phonemes (Phoneme oy) (Phonemes (Phoneme s)))))))
(Colloc0#6 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme l) (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))))))
(Colloc0#4 (Phonemes (Phoneme p)))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme iy))))))
(Colloc0#8 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme iy) (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))))))
(Colloc0#9 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme er) (Phonemes (Phoneme p)))))
(Colloc0#10 (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#9 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))
(Colloc0#14 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#1 (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme th) (Phonemes (Phoneme r)))))))
(Colloc0#4 (Phonemes (Phoneme ch) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme th)))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme ow)))))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme z))))))
