825	Sentence --> Colloc0s
454	Colloc0 --> Phonemes
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#18 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme l)))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#10 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme y) (Phonemes (Phoneme uw) (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme ay)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#9 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#15 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme aa))))
(Colloc0#19 (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax)))))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme er))))))
(Colloc0#31 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g)))))
(Colloc0#7 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#1 (Phonemes (Phoneme l)))
(Colloc0#62 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))))
(Colloc0#29 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#16 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme m))))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme g)))))
(Colloc0#6 (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme sh)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme y) (Phonemes (Phoneme uw)))))))
(Colloc0#10 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme w)))
(Colloc0#1 (Phonemes (Phoneme w)))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme t)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))))
(Colloc0#9 (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#77 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#10 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#9 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))))
(Colloc0#28 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme d) (Phonemes (Phoneme iy)))))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme z) (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme r))))))))))
(Colloc0#15 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k) (Phonemes (Phoneme er))))))
(Colloc0#5 (Phonemes (Phoneme uh) (Phonemes (Phoneme sh) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m) (Phonemes (Phoneme ih))))))))
(Colloc0#6 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s) (Phonemes (Phoneme dh)))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme z) (Phonemes (Phoneme d)))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k))))))))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme uh) (Phonemes (Phoneme d) (Phonemes (Phoneme ay))))))
(Colloc0#20 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme er))))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#11 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme r)))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))
(Colloc0#9 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme aw))))
(Colloc0#15 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#8 (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#13 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#5 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme ax)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme ch) (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme r))))
(Colloc0#3 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#11 (Phonemes (Phoneme t)))
(Colloc0#7 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme oy))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme oy) (Phonemes (Phoneme z)))))
(Colloc0#23 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))))
(Colloc0#7 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ey))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme er) (Phonemes (Phoneme d))))))
(Colloc0#8 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme k)))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme n) (Phonemes (Phoneme dh))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))
(Colloc0#7 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme ih)))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#47 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#75 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))))))
(Colloc0#23 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#22 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#18 (Phonemes (Phoneme ax)))
(Colloc0#6 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))))
(Colloc0#6 (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ey)))))
(Colloc0#13 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw)))))
(Colloc0#7 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))))
(Colloc0#14 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme s)))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme k))))))
(Colloc0#15 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme f))))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh))))))
(Colloc0#11 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme r)))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme b)))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#37 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#13 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme z)))))))
(Colloc0#6 (Phonemes (Phoneme b) (Phonemes (Phoneme ay))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#6 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme th) (Phonemes (Phoneme ah) (Phonemes (Phoneme v)))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#3 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme ng)))
(Colloc0#1 (Phonemes (Phoneme ng)))
(Colloc0#1 (Phonemes (Phoneme hh)))
(Colloc0#15 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme hh) (Phonemes (Phoneme er) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme jh) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))))))))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme p) (Phonemes (Phoneme ax))))))
(Colloc0#15 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#11 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#38 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme k))))))))
(Colloc0#20 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#30 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#25 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#47 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme b) (Phonemes (Phoneme aw) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax)))))))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#85 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme l)))))
(Colloc0#2 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#27 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s)))))
(Colloc0#7 (Phonemes (Phoneme ay)))
(Colloc0#8 (Phonemes (Phoneme ay)))
(Colloc0#4 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme d) (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))))
(Colloc0#6 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme ae) (Phonemes (Phoneme m)))))
(Colloc0#11 (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#13 (Phonemes (Phoneme ay) (Phonemes (Phoneme m) (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))))
(Colloc0#6 (Phonemes (Phoneme ay) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#24 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#14 (Phonemes (Phoneme s)))
(Colloc0#9 (Phonemes (Phoneme s)))
(Colloc0#5 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#6 (Phonemes (Phoneme s)))
(Colloc0#14 (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p))))))
(Colloc0#7 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh)))))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ey)))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme l))))))
(Colloc0#17 (Phonemes (Phoneme s) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s))))))
(Colloc0#15 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme th))))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme z)))))
(Colloc0#25 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#22 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme er))))))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme ih) (Phonemes (Phoneme f))))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n))))))))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#3 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#4 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#5 (Phonemes (Phoneme n)))
(Colloc0#4 (Phonemes (Phoneme n)))
(Colloc0#7 (Phonemes (Phoneme n)))
(Colloc0#13 (Phonemes (Phoneme n)))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme p) (Phonemes (Phoneme aa))))))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#13 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme m)))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))
(Colloc0#15 (Phonemes (Phoneme n) (Phonemes (Phoneme z))))
(Colloc0#10 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#5 (Phonemes (Phoneme n) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))
(Colloc0#16 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#7 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#5 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#1 (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch)))))
(Colloc0#13 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme ch) (Phonemes (Phoneme iy)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme z))))))
(Colloc0#8 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ay) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z)))))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme ay) (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er)))))))
(Colloc0#11 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#7 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er))))))
(Colloc0#20 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#6 (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme th)))))
(Colloc0#1 (Phonemes (Phoneme er)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#18 (Phonemes (Phoneme z)))
(Colloc0#5 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#4 (Phonemes (Phoneme z) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax)))))
(Colloc0#12 (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme p)))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme z) (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme iy)))))))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme ow)))
(Colloc0#18 (Phonemes (Phoneme ow)))
(Colloc0#2 (Phonemes (Phoneme ow)))
(Colloc0#22 (Phonemes (Phoneme ow)))
(Colloc0#33 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme ay) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme ow) (Phonemes (Phoneme p))))
(Colloc0#6 (Phonemes (Phoneme p)))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme z))))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))))
(Colloc0#34 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#7 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g))))))))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh))))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#13 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme v) (Phonemes (Phoneme m) (Phonemes (Phoneme iy)))))))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme d))))
(Colloc0#3 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#13 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#22 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme ey) (Phonemes (Phoneme l)))))
(Colloc0#10 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#13 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#7 (Phonemes (Phoneme g) (Phonemes (Phoneme ow) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#12 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#3 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae)))))
(Colloc0#24 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ao) (Phonemes (Phoneme n)))))
(Colloc0#7 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme b) (Phonemes (Phoneme iy)))))
(Colloc0#5 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ey)))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme ch)))
(Colloc0#2 (Phonemes (Phoneme ch)))
(Colloc0#6 (Phonemes (Phoneme ch) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme ch) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#1 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme dh) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme uw))))
(Colloc0#5 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#13 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#13 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#15 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#24 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy)))
(Colloc0#3 (Phonemes (Phoneme iy)))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#5 (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme d)))))))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme ax)))))))
(Colloc0#3 (Phonemes (Phoneme iy) (Phonemes (Phoneme uw) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))))))
(Colloc0#9 (Phonemes (Phoneme iy) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))))
(Colloc0#32 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme ax))))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#13 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#18 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme uw) (Phonemes (Phoneme t))))))
(Colloc0#17 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme p))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme g))))
(Colloc0#13 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#16 (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#2 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#3 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#15 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#5 (Phonemes (Phoneme aw) (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))))
(Colloc0#3 (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#7 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme ow))))
(Colloc0#5 (Phonemes (Phoneme f)))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme l))))
(Colloc0#5 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme z))))))
(Colloc0#8 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#9 (Phonemes (Phoneme f) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme m))))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme er)))))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ao))))))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#5 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
2246	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
941	Phonemes --> Phoneme Phonemes
454	Phonemes --> Phoneme
60	Phoneme --> r
43	Phoneme --> ay
31	Phoneme --> aa
33	Phoneme --> hh
10	Phoneme --> uh
39	Phoneme --> ah
9	Phoneme --> ch
100	Phoneme --> t
50	Phoneme --> z
62	Phoneme --> l
80	Phoneme --> ax
1	Phoneme --> zh
10	Phoneme --> th
24	Phoneme --> f
22	Phoneme --> uw
29	Phoneme --> p
4	Phoneme --> oy
15	Phoneme --> ng
23	Phoneme --> ao
78	Phoneme --> n
61	Phoneme --> ih
43	Phoneme --> eh
34	Phoneme --> ae
16	Phoneme --> aw
27	Phoneme --> er
53	Phoneme --> d
26	Phoneme --> dh
32	Phoneme --> w
27	Phoneme --> ow
12	Phoneme --> v
70	Phoneme --> s
74	Phoneme --> iy
12	Phoneme --> y
66	Phoneme --> k
24	Phoneme --> g
50	Phoneme --> m
9	Phoneme --> sh
7	Phoneme --> jh
29	Phoneme --> ey
38	Phoneme --> b
