825	Sentence --> Colloc0s
423	Colloc0 --> Phonemes
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#1 (Phonemes (Phoneme d)))
(Colloc0#2 (Phonemes (Phoneme d)))
(Colloc0#18 (Phonemes (Phoneme d) (Phonemes (Phoneme ey) (Phonemes (Phoneme l)))))
(Colloc0#14 (Phonemes (Phoneme d) (Phonemes (Phoneme ae) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#12 (Phonemes (Phoneme d) (Phonemes (Phoneme uw))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme uw) (Phonemes (Phoneme ay)))))
(Colloc0#2 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#9 (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme z)))))
(Colloc0#15 (Phonemes (Phoneme d) (Phonemes (Phoneme ow) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme aa))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))
(Colloc0#3 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))))
(Colloc0#1 (Phonemes (Phoneme d) (Phonemes (Phoneme iy) (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))))
(Colloc0#5 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme d)))))
(Colloc0#8 (Phonemes (Phoneme d) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme er))))))
(Colloc0#38 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme g) (Phonemes (Phoneme iy))))))
(Colloc0#4 (Phonemes (Phoneme d) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#6 (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#2 (Phonemes (Phoneme l)))
(Colloc0#48 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#14 (Phonemes (Phoneme l) (Phonemes (Phoneme uh) (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh))))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme ax) (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))))
(Colloc0#31 (Phonemes (Phoneme l) (Phonemes (Phoneme ay) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme ch))))))
(Colloc0#8 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#16 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme uw) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme eh) (Phonemes (Phoneme g)))))
(Colloc0#5 (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))
(Colloc0#4 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#10 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l)))))))
(Colloc0#1 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#2 (Phonemes (Phoneme l) (Phonemes (Phoneme ih) (Phonemes (Phoneme f) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#2 (Phonemes (Phoneme w)))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))
(Colloc0#5 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme t)))))
(Colloc0#6 (Phonemes (Phoneme w) (Phonemes (Phoneme ey) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))
(Colloc0#9 (Phonemes (Phoneme w) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#11 (Phonemes (Phoneme w) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ay) (Phonemes (Phoneme ax) (Phonemes (Phoneme t))))))
(Colloc0#60 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#17 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme t) (Phonemes (Phoneme s) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#12 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n)))))
(Colloc0#19 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t))))))
(Colloc0#26 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme z)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme hh) (Phonemes (Phoneme iy)))))))
(Colloc0#3 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme d) (Phonemes (Phoneme iy)))))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme z))))))
(Colloc0#4 (Phonemes (Phoneme w) (Phonemes (Phoneme iy))))
(Colloc0#8 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#9 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme iy) (Phonemes (Phoneme aa)))))
(Colloc0#2 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme l)))))
(Colloc0#7 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme dh)))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme er)))))))
(Colloc0#1 (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme uh) (Phonemes (Phoneme d))))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#7 (Phonemes (Phoneme k)))
(Colloc0#1 (Phonemes (Phoneme k)))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#2 (Phonemes (Phoneme k) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae)))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ih) (Phonemes (Phoneme k))))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme k) (Phonemes (Phoneme w) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))))
(Colloc0#20 (Phonemes (Phoneme k) (Phonemes (Phoneme ae) (Phonemes (Phoneme n)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme l) (Phonemes (Phoneme er))))))
(Colloc0#8 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme p) (Phonemes (Phoneme s))))))
(Colloc0#11 (Phonemes (Phoneme k) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme aa) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme f) (Phonemes (Phoneme ax)))))))
(Colloc0#5 (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme z))))))))
(Colloc0#1 (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme k) (Phonemes (Phoneme iy) (Phonemes (Phoneme p)))))
(Colloc0#13 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy))))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ih) (Phonemes (Phoneme s)))))
(Colloc0#7 (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme l)))))
(Colloc0#6 (Phonemes (Phoneme k) (Phonemes (Phoneme aw))))
(Colloc0#14 (Phonemes (Phoneme ae) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme m)))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme n))))
(Colloc0#16 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))))
(Colloc0#1 (Phonemes (Phoneme ae) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#2 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#1 (Phonemes (Phoneme t)))
(Colloc0#7 (Phonemes (Phoneme t) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme oy))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme oy) (Phonemes (Phoneme z)))))
(Colloc0#25 (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))
(Colloc0#7 (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme uw))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#6 (Phonemes (Phoneme t) (Phonemes (Phoneme ay) (Phonemes (Phoneme m)))))
(Colloc0#8 (Phonemes (Phoneme t) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme t) (Phonemes (Phoneme er) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme aa))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme t) (Phonemes (Phoneme f) (Phonemes (Phoneme r))))))))
(Colloc0#5 (Phonemes (Phoneme t) (Phonemes (Phoneme eh))))
(Colloc0#2 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ay)))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme k))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme k) (Phonemes (Phoneme s)))))))
(Colloc0#3 (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#4 (Phonemes (Phoneme t) (Phonemes (Phoneme ao) (Phonemes (Phoneme k)))))
(Colloc0#4 (Phonemes (Phoneme dh)))
(Colloc0#7 (Phonemes (Phoneme dh) (Phonemes (Phoneme ey))))
(Colloc0#40 (Phonemes (Phoneme dh) (Phonemes (Phoneme ae) (Phonemes (Phoneme t)))))
(Colloc0#72 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))
(Colloc0#16 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))))))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t))))))))
(Colloc0#19 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))))))))
(Colloc0#4 (Phonemes (Phoneme dh) (Phonemes (Phoneme er) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme dh) (Phonemes (Phoneme ow) (Phonemes (Phoneme z)))))
(Colloc0#22 (Phonemes (Phoneme dh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#8 (Phonemes (Phoneme dh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#4 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#4 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#12 (Phonemes (Phoneme ax)))
(Colloc0#5 (Phonemes (Phoneme ax)))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme aa)))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme d) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme t))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme sh))))))
(Colloc0#3 (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ao) (Phonemes (Phoneme k))))))
(Colloc0#11 (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k))))))
(Colloc0#19 (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme hh) (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))))
(Colloc0#12 (Phonemes (Phoneme ax) (Phonemes (Phoneme s))))
(Colloc0#13 (Phonemes (Phoneme ax) (Phonemes (Phoneme n))))
(Colloc0#2 (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme p)))))))
(Colloc0#4 (Phonemes (Phoneme ax) (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme er)))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme l))))))
(Colloc0#11 (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme n))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme uw) (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))))
(Colloc0#1 (Phonemes (Phoneme ax) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme r)))))))))
(Colloc0#2 (Phonemes (Phoneme b)))
(Colloc0#2 (Phonemes (Phoneme b)))
(Colloc0#1 (Phonemes (Phoneme b)))
(Colloc0#12 (Phonemes (Phoneme b) (Phonemes (Phoneme l) (Phonemes (Phoneme aa) (Phonemes (Phoneme k))))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme oy))))
(Colloc0#26 (Phonemes (Phoneme b) (Phonemes (Phoneme uh) (Phonemes (Phoneme k)))))
(Colloc0#13 (Phonemes (Phoneme b) (Phonemes (Phoneme ae) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme k) (Phonemes (Phoneme ao) (Phonemes (Phoneme z)))))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ay))))
(Colloc0#7 (Phonemes (Phoneme b) (Phonemes (Phoneme ay) (Phonemes (Phoneme eh) (Phonemes (Phoneme b) (Phonemes (Phoneme iy)))))))
(Colloc0#11 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme t)))))
(Colloc0#15 (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme ow) (Phonemes (Phoneme th)))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme aa) (Phonemes (Phoneme k) (Phonemes (Phoneme s))))))
(Colloc0#3 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme t) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme b) (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#5 (Phonemes (Phoneme b) (Phonemes (Phoneme r) (Phonemes (Phoneme ah) (Phonemes (Phoneme sh))))))
(Colloc0#4 (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme g)))))
(Colloc0#2 (Phonemes (Phoneme b) (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme z))))))
(Colloc0#1 (Phonemes (Phoneme v)))
(Colloc0#3 (Phonemes (Phoneme v) (Phonemes (Phoneme eh) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))
(Colloc0#8 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme v)))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme p)))))
(Colloc0#15 (Phonemes (Phoneme hh) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#9 (Phonemes (Phoneme hh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z) (Phonemes (Phoneme dh))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay))))
(Colloc0#4 (Phonemes (Phoneme hh) (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme ax))))))
(Colloc0#38 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah))))
(Colloc0#22 (Phonemes (Phoneme hh) (Phonemes (Phoneme ah) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme iy))))))))
(Colloc0#2 (Phonemes (Phoneme hh) (Phonemes (Phoneme er))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ow) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#7 (Phonemes (Phoneme hh) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#10 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy))))
(Colloc0#21 (Phonemes (Phoneme hh) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))
(Colloc0#25 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme w) (Phonemes (Phoneme ey))))))))
(Colloc0#20 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z)))))
(Colloc0#50 (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme r)))))
(Colloc0#12 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw))))
(Colloc0#14 (Phonemes (Phoneme hh) (Phonemes (Phoneme aw) (Phonemes (Phoneme s)))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme ae))))
(Colloc0#90 (Phonemes (Phoneme y) (Phonemes (Phoneme uw))))
(Colloc0#9 (Phonemes (Phoneme y) (Phonemes (Phoneme aa))))
(Colloc0#1 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme ow))))))
(Colloc0#17 (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme s)))))
(Colloc0#30 (Phonemes (Phoneme y) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#4 (Phonemes (Phoneme uw) (Phonemes (Phoneme p) (Phonemes (Phoneme s)))))
(Colloc0#3 (Phonemes (Phoneme ay)))
(Colloc0#11 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay)))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme d))))
(Colloc0#7 (Phonemes (Phoneme ay) (Phonemes (Phoneme l))))
(Colloc0#4 (Phonemes (Phoneme ay) (Phonemes (Phoneme w) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme t)))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme ae) (Phonemes (Phoneme m)))))
(Colloc0#11 (Phonemes (Phoneme ay) (Phonemes (Phoneme t) (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#21 (Phonemes (Phoneme ay) (Phonemes (Phoneme m))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme er) (Phonemes (Phoneme d)))))
(Colloc0#3 (Phonemes (Phoneme ay) (Phonemes (Phoneme z))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme g))))
(Colloc0#2 (Phonemes (Phoneme ay) (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme k)))))))
(Colloc0#1 (Phonemes (Phoneme ay) (Phonemes (Phoneme f))))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#7 (Phonemes (Phoneme s)))
(Colloc0#2 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#28 (Phonemes (Phoneme s)))
(Colloc0#1 (Phonemes (Phoneme s)))
(Colloc0#10 (Phonemes (Phoneme s)))
(Colloc0#8 (Phonemes (Phoneme s)))
(Colloc0#4 (Phonemes (Phoneme s)))
(Colloc0#14 (Phonemes (Phoneme s) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme p))))))
(Colloc0#15 (Phonemes (Phoneme s) (Phonemes (Phoneme ey))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme ey) (Phonemes (Phoneme ch)))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme k) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme ch)))))))
(Colloc0#4 (Phonemes (Phoneme s) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ah)))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme ax)))))))
(Colloc0#15 (Phonemes (Phoneme s) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))
(Colloc0#5 (Phonemes (Phoneme s) (Phonemes (Phoneme ay) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme ah) (Phonemes (Phoneme ch) (Phonemes (Phoneme iy))))))
(Colloc0#8 (Phonemes (Phoneme s) (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme l))))))
(Colloc0#6 (Phonemes (Phoneme s) (Phonemes (Phoneme ow))))
(Colloc0#2 (Phonemes (Phoneme s) (Phonemes (Phoneme eh) (Phonemes (Phoneme z)))))
(Colloc0#34 (Phonemes (Phoneme s) (Phonemes (Phoneme iy))))
(Colloc0#19 (Phonemes (Phoneme s) (Phonemes (Phoneme iy) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#1 (Phonemes (Phoneme s) (Phonemes (Phoneme ih) (Phonemes (Phoneme n)))))
(Colloc0#7 (Phonemes (Phoneme n)))
(Colloc0#3 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#2 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#2 (Phonemes (Phoneme n)))
(Colloc0#1 (Phonemes (Phoneme n)))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme ey) (Phonemes (Phoneme m)))))
(Colloc0#11 (Phonemes (Phoneme n) (Phonemes (Phoneme t))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme y) (Phonemes (Phoneme eh) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ay) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme z))))))))
(Colloc0#8 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#7 (Phonemes (Phoneme n) (Phonemes (Phoneme ow))))
(Colloc0#4 (Phonemes (Phoneme n) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme eh) (Phonemes (Phoneme k)))))
(Colloc0#2 (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))
(Colloc0#15 (Phonemes (Phoneme n) (Phonemes (Phoneme aw))))
(Colloc0#7 (Phonemes (Phoneme ah) (Phonemes (Phoneme dh) (Phonemes (Phoneme er)))))
(Colloc0#14 (Phonemes (Phoneme ah) (Phonemes (Phoneme v))))
(Colloc0#2 (Phonemes (Phoneme ah) (Phonemes (Phoneme m) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ax) (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng)))))))))))))
(Colloc0#13 (Phonemes (Phoneme ah) (Phonemes (Phoneme p))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#5 (Phonemes (Phoneme m) (Phonemes (Phoneme ey) (Phonemes (Phoneme b) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme k)))))
(Colloc0#8 (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme iy))))))
(Colloc0#15 (Phonemes (Phoneme m) (Phonemes (Phoneme ay))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme ay) (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme ow) (Phonemes (Phoneme t))))))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme aa))))
(Colloc0#3 (Phonemes (Phoneme m) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme z)))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme b) (Phonemes (Phoneme er)))))))
(Colloc0#12 (Phonemes (Phoneme m) (Phonemes (Phoneme iy))))
(Colloc0#10 (Phonemes (Phoneme m) (Phonemes (Phoneme iy) (Phonemes (Phoneme t)))))
(Colloc0#4 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme ax) (Phonemes (Phoneme t)))))))
(Colloc0#2 (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme uw) (Phonemes (Phoneme t)))))))
(Colloc0#20 (Phonemes (Phoneme m) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme th)))))
(Colloc0#6 (Phonemes (Phoneme er) (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#76 (Phonemes (Phoneme z)))
(Colloc0#5 (Phonemes (Phoneme z)))
(Colloc0#1 (Phonemes (Phoneme z)))
(Colloc0#5 (Phonemes (Phoneme z) (Phonemes (Phoneme ax))))
(Colloc0#7 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme g) (Phonemes (Phoneme iy))))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ax) (Phonemes (Phoneme r)))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme g) (Phonemes (Phoneme ow) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng) (Phonemes (Phoneme n))))))))
(Colloc0#3 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme z) (Phonemes (Phoneme ih) (Phonemes (Phoneme p) (Phonemes (Phoneme ih) (Phonemes (Phoneme t)))))))
(Colloc0#4 (Phonemes (Phoneme ow)))
(Colloc0#34 (Phonemes (Phoneme ow)))
(Colloc0#33 (Phonemes (Phoneme ow) (Phonemes (Phoneme k) (Phonemes (Phoneme ey)))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme v) (Phonemes (Phoneme er)))))
(Colloc0#3 (Phonemes (Phoneme ow) (Phonemes (Phoneme ow))))
(Colloc0#1 (Phonemes (Phoneme p)))
(Colloc0#2 (Phonemes (Phoneme p)))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme l) (Phonemes (Phoneme ey)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme ey) (Phonemes (Phoneme jh)))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme l)))))
(Colloc0#41 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme p) (Phonemes (Phoneme uh) (Phonemes (Phoneme sh) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme m) (Phonemes (Phoneme ih)))))))))
(Colloc0#6 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme t) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme ah) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))))))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))))
(Colloc0#1 (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme p) (Phonemes (Phoneme uw) (Phonemes (Phoneme n)))))
(Colloc0#4 (Phonemes (Phoneme p) (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme iy)))))))
(Colloc0#13 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme b) (Phonemes (Phoneme uw))))))))
(Colloc0#3 (Phonemes (Phoneme p) (Phonemes (Phoneme iy) (Phonemes (Phoneme s)))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme d) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme ax) (Phonemes (Phoneme n) (Phonemes (Phoneme ah) (Phonemes (Phoneme f))))))))))
(Colloc0#16 (Phonemes (Phoneme aa) (Phonemes (Phoneme n))))
(Colloc0#12 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#7 (Phonemes (Phoneme aa) (Phonemes (Phoneme r))))
(Colloc0#1 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme d) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))))
(Colloc0#2 (Phonemes (Phoneme aa) (Phonemes (Phoneme r) (Phonemes (Phoneme p) (Phonemes (Phoneme ao) (Phonemes (Phoneme l) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme jh) (Phonemes (Phoneme uw))))))))))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme ey) (Phonemes (Phoneme l)))))
(Colloc0#10 (Phonemes (Phoneme g) (Phonemes (Phoneme uh) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme er) (Phonemes (Phoneme l)))))
(Colloc0#17 (Phonemes (Phoneme g) (Phonemes (Phoneme ow))))
(Colloc0#4 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme t)))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme aa) (Phonemes (Phoneme n) (Phonemes (Phoneme ax))))))
(Colloc0#12 (Phonemes (Phoneme g) (Phonemes (Phoneme eh) (Phonemes (Phoneme t)))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme p) (Phonemes (Phoneme aa)))))))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme m) (Phonemes (Phoneme ax)))))))
(Colloc0#2 (Phonemes (Phoneme g) (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme n))))))
(Colloc0#5 (Phonemes (Phoneme g) (Phonemes (Phoneme ih) (Phonemes (Phoneme v)))))
(Colloc0#1 (Phonemes (Phoneme g) (Phonemes (Phoneme ao) (Phonemes (Phoneme n)))))
(Colloc0#7 (Phonemes (Phoneme eh) (Phonemes (Phoneme l) (Phonemes (Phoneme s)))))
(Colloc0#4 (Phonemes (Phoneme eh) (Phonemes (Phoneme s))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme ax)))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme s) (Phonemes (Phoneme eh)))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme eh) (Phonemes (Phoneme m))))
(Colloc0#2 (Phonemes (Phoneme eh) (Phonemes (Phoneme m) (Phonemes (Phoneme ih) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme eh) (Phonemes (Phoneme r))))
(Colloc0#6 (Phonemes (Phoneme ch) (Phonemes (Phoneme eh) (Phonemes (Phoneme r)))))
(Colloc0#1 (Phonemes (Phoneme ch) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ax) (Phonemes (Phoneme n)))))))
(Colloc0#3 (Phonemes (Phoneme ch) (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme ay) (Phonemes (Phoneme z)))))))
(Colloc0#1 (Phonemes (Phoneme th)))
(Colloc0#7 (Phonemes (Phoneme th) (Phonemes (Phoneme ae) (Phonemes (Phoneme ng) (Phonemes (Phoneme k))))))
(Colloc0#4 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme uw)))))
(Colloc0#2 (Phonemes (Phoneme th) (Phonemes (Phoneme r) (Phonemes (Phoneme iy)))))
(Colloc0#5 (Phonemes (Phoneme th) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#1 (Phonemes (Phoneme r)))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ey))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme dh) (Phonemes (Phoneme er))))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ae) (Phonemes (Phoneme g) (Phonemes (Phoneme ax))))))
(Colloc0#21 (Phonemes (Phoneme r) (Phonemes (Phoneme ay) (Phonemes (Phoneme t)))))
(Colloc0#7 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d)))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d) (Phonemes (Phoneme m) (Phonemes (Phoneme iy)))))))
(Colloc0#4 (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#1 (Phonemes (Phoneme r) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#2 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme l) (Phonemes (Phoneme iy))))))
(Colloc0#16 (Phonemes (Phoneme r) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng)))))
(Colloc0#6 (Phonemes (Phoneme iy)))
(Colloc0#1 (Phonemes (Phoneme iy)))
(Colloc0#5 (Phonemes (Phoneme iy) (Phonemes (Phoneme t))))
(Colloc0#5 (Phonemes (Phoneme iy) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme ng))))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme b) (Phonemes (Phoneme er) (Phonemes (Phoneme d) (Phonemes (Phoneme iy)))))))
(Colloc0#1 (Phonemes (Phoneme iy) (Phonemes (Phoneme b) (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme d)))))))
(Colloc0#2 (Phonemes (Phoneme iy) (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme s))))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme k) (Phonemes (Phoneme t) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))))
(Colloc0#36 (Phonemes (Phoneme ih) (Phonemes (Phoneme t))))
(Colloc0#7 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme d) (Phonemes (Phoneme aw) (Phonemes (Phoneme n)))))))
(Colloc0#1 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme k) (Phonemes (Phoneme l) (Phonemes (Phoneme ow)))))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme ax) (Phonemes (Phoneme l) (Phonemes (Phoneme k) (Phonemes (Phoneme ah) (Phonemes (Phoneme m)))))))))
(Colloc0#10 (Phonemes (Phoneme ih) (Phonemes (Phoneme t) (Phonemes (Phoneme s)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme ng))))
(Colloc0#11 (Phonemes (Phoneme ih) (Phonemes (Phoneme n))))
(Colloc0#14 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax))))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme dh) (Phonemes (Phoneme ax) (Phonemes (Phoneme m)))))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme n) (Phonemes (Phoneme hh) (Phonemes (Phoneme ih) (Phonemes (Phoneme z) (Phonemes (Phoneme m) (Phonemes (Phoneme aw) (Phonemes (Phoneme th))))))))))
(Colloc0#17 (Phonemes (Phoneme ih) (Phonemes (Phoneme z))))
(Colloc0#5 (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme er)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme r) (Phonemes (Phoneme z)))))
(Colloc0#2 (Phonemes (Phoneme ih) (Phonemes (Phoneme f))))
(Colloc0#31 (Phonemes (Phoneme ao) (Phonemes (Phoneme l))))
(Colloc0#2 (Phonemes (Phoneme ao) (Phonemes (Phoneme r))))
(Colloc0#3 (Phonemes (Phoneme ao) (Phonemes (Phoneme f))))
(Colloc0#1 (Phonemes (Phoneme aw) (Phonemes (Phoneme l))))
(Colloc0#28 (Phonemes (Phoneme aw) (Phonemes (Phoneme t))))
(Colloc0#3 (Phonemes (Phoneme aw) (Phonemes (Phoneme n) (Phonemes (Phoneme d)))))
(Colloc0#5 (Phonemes (Phoneme jh) (Phonemes (Phoneme uw) (Phonemes (Phoneme d) (Phonemes (Phoneme iy))))))
(Colloc0#8 (Phonemes (Phoneme jh) (Phonemes (Phoneme ah) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#1 (Phonemes (Phoneme jh) (Phonemes (Phoneme ow) (Phonemes (Phoneme iy)))))
(Colloc0#3 (Phonemes (Phoneme f)))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme ow) (Phonemes (Phoneme t))))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme l) (Phonemes (Phoneme aw) (Phonemes (Phoneme er))))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ey) (Phonemes (Phoneme k)))))
(Colloc0#9 (Phonemes (Phoneme f) (Phonemes (Phoneme uw) (Phonemes (Phoneme d)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ay) (Phonemes (Phoneme v)))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ah) (Phonemes (Phoneme n)))))
(Colloc0#2 (Phonemes (Phoneme f) (Phonemes (Phoneme er) (Phonemes (Phoneme s) (Phonemes (Phoneme t))))))
(Colloc0#4 (Phonemes (Phoneme f) (Phonemes (Phoneme ow) (Phonemes (Phoneme n)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme r) (Phonemes (Phoneme eh) (Phonemes (Phoneme n) (Phonemes (Phoneme d) (Phonemes (Phoneme l) (Phonemes (Phoneme iy) (Phonemes (Phoneme d))))))))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme d)))))
(Colloc0#6 (Phonemes (Phoneme f) (Phonemes (Phoneme iy) (Phonemes (Phoneme l)))))
(Colloc0#1 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme k)))))
(Colloc0#7 (Phonemes (Phoneme f) (Phonemes (Phoneme ih) (Phonemes (Phoneme ng) (Phonemes (Phoneme g) (Phonemes (Phoneme er)))))))
(Colloc0#10 (Phonemes (Phoneme f) (Phonemes (Phoneme ao) (Phonemes (Phoneme r)))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme ae) (Phonemes (Phoneme l) (Phonemes (Phoneme ay))))))
(Colloc0#2 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw))))
(Colloc0#8 (Phonemes (Phoneme sh) (Phonemes (Phoneme uw) (Phonemes (Phoneme z)))))
(Colloc0#3 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy))))
(Colloc0#1 (Phonemes (Phoneme sh) (Phonemes (Phoneme iy) (Phonemes (Phoneme hh) (Phonemes (Phoneme ae) (Phonemes (Phoneme z) (Phonemes (Phoneme hh) (Phonemes (Phoneme er) (Phonemes (Phoneme p) (Phonemes (Phoneme ax) (Phonemes (Phoneme jh) (Phonemes (Phoneme aa) (Phonemes (Phoneme m) (Phonemes (Phoneme ax) (Phonemes (Phoneme z))))))))))))))))
2162	Colloc0s --> Colloc0 Colloc0s
825	Colloc0s --> Colloc0
941	Phonemes --> Phoneme Phonemes
423	Phonemes --> Phoneme
62	Phoneme --> r
39	Phoneme --> ay
34	Phoneme --> aa
32	Phoneme --> hh
11	Phoneme --> uh
33	Phoneme --> ah
8	Phoneme --> ch
94	Phoneme --> t
40	Phoneme --> z
61	Phoneme --> l
88	Phoneme --> ax
1	Phoneme --> zh
11	Phoneme --> th
27	Phoneme --> f
19	Phoneme --> uw
31	Phoneme --> p
4	Phoneme --> oy
13	Phoneme --> ng
18	Phoneme --> ao
83	Phoneme --> n
62	Phoneme --> ih
43	Phoneme --> eh
36	Phoneme --> ae
14	Phoneme --> aw
29	Phoneme --> er
57	Phoneme --> d
26	Phoneme --> dh
35	Phoneme --> w
27	Phoneme --> ow
9	Phoneme --> v
59	Phoneme --> s
70	Phoneme --> iy
9	Phoneme --> y
65	Phoneme --> k
26	Phoneme --> g
46	Phoneme --> m
9	Phoneme --> sh
8	Phoneme --> jh
26	Phoneme --> ey
37	Phoneme --> b
